name: StackableItems
author: haveric
main: haveric.stackableItems.StackableItems
version: 1.0.3
website: http://dev.bukkit.org/server-mods/stackableitems/
dev-url: http://dev.bukkit.org/server-mods/stackableitems/
softdepend: [Vault]
commands:
    stackableitems:
        aliases: [si]
        description: Allows you to change any item's max stack amount.
        usage:
        
permissions:
    stackableitems.*:
        description: Gives access to all StackableItems Commands
        children:
            stackableitems.stack: true
            stackableitems.admin: true
    stackableitems.stack:
        description: Allows a permission group to stack items.
        default: false
    stackableitems.admin:
        description: Allows use of admin commands.
        default: false